config/routes.rb
Clase4::Application.routes.draw do
  devise_for :users

  get "home/index"
  resources :holidays
  resources :clients
  match 'configurar'=>'home#configurar', :as => :configurar
  match 'actualizar'=>'home#actualizar_usuario', :as => :actualizar_usuario
  match 'sending_email' => 'home#send_email_test', :as => :sending_email

  root :to => 'home#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to :user
  has_many :notifications
  attr_accessible :company_name, :contact_name, :contact_surname, :email
  validates :email, :uniqueness => true, :presence => true
  validates :contact_name, :presence => true

  def full_name
  	contact_name+' ' + contact_surname
  end

  
end

app/models/holiday.rb
#encoding=utf-8
class Holiday < ActiveRecord::Base
  belongs_to :user
  has_many :notifications
  attr_accessible :date, :description
  validates :description, :presence => true
  validates :user_id, :uniqueness => { :scope => :date, :message => "Ya fué ingresada esta fecha"}

  # Devuelve una etiqueta con la fecha y descripción del feriado
  def label_holiday
  	"#{date} (#{description})"
  end

  def notify
  	self.notified = true
  	self.save #¿está bien hacer esto?
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :client
  belongs_to :holiday
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :first_name, :last_name, :days, :message
  
  # attr_accessible :title, :body

  has_many :holidays
  has_many :clients

  # Informa si el cliente tiene un feriado que aún no haya sido anunciado a su cliente via email
  # Devuelve:
  # * true: si el cliente tiene un feriado dentro de los días especificados en days que aún no fué notificado via email al cliente.
  # * false:
  #     ** si el cliente No tiene feriado dentro delos días especificados en days. 
  #     ** si el cliente tiene feriado dentro delos días especificados en days, pero ya fué notificado via email. 
  #     ** Si el cliente aún no especificó los días de anticipacion con los que se deberá notificar en el campo days.
  # def any_holiday?    
  #   return false if days.nil?
  #   self.holidays.each do |holiday|
  #     if (holiday.date == (Date.today + self.days) and holiday.notified == false)               
  #       return true
  #     end
  #   end
  #   return false
  # end
  def any_holiday?  	
  	return false if days.nil?
  	self.holidays.each do |holiday|
  		if (holiday.date == (Date.today + self.days))
  			return true
  		end
  	end
  	return false
  end



  # Devuelve el feriado del usuario que vendrá dentro de los días especificados en days. 
  # Debido a que las fechas no se repiten dentro del calendario personal del usuario, puedo usar a la fecha como parámetro de búsqueda.
  def holiday
    # No pueden existir dos o mas feriados para un usuario con la misma fecha, por ello, el primer elemento del resultado de la búsqueda será el adecuado.
    self.holidays.where(:date => Date.today + self.days).first
  end

  def self.envio_masivo
    User.all.each do |user|
      if user.any_holiday?
          user.clients.each do |client|
            unless Notification.where(:holiday =>  user.holiday, :client => client)
              if NewsletterMailer.weekly("#{user.email}","#{client.email}","#{user.holiday.label_holiday}").deliver
                #user.holiday.notify                
                Notification.create(:client => client, :user => user)
              end
            end
          end
      end    
    end
  end

end

app/controllers/application_controller.rb
#encoding=utf-8
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :cargar_usuario

  def cargar_usuario
  	@user = User.new
  end
end

app/controllers/clients_controller.rb
class ClientsController < InheritedResources::Base
	before_filter :authenticate_user!
	def begin_of_association_chain
		current_user
	end
	def collection
		get_collection_ivar || set_collection_ivar(end_of_association_chain.paginate(:page => params[:page], :per_page => per_page))
	end

	def per_page
		3
	end

	def create
		create!{clients_path}
	end
	def update
		update!{clients_path}
	end

end

app/controllers/holidays_controller.rb
class HolidaysController < InheritedResources::Base
	before_filter :authenticate_user!

	# belongs_to :user
	# actions :index, :new, :create
	#protected
	def begin_of_association_chain
		current_user
	end

	def collection
		#@holidays ||= end_of_association_chain.paginate(:page => params[:page])
		# @holidays ||= end_of_association_chain.paginate(:params[:page]).all
		get_collection_ivar || set_collection_ivar(end_of_association_chain.paginate(:page => params[:page], :per_page => per_page))
	end

	def per_page
		3
	end

	def create
		create!{holidays_path}
	end
	def update
		update!{holidays_path}
	end

	# def create
	# 	create!{colletion_url}
	# end

	# ApplicationController
	# def index
	# 	@holidays = current_user.holidays
	# end

	# def new 
	# 	@holiday = current_user.holidays.new
	# end

	# def edit
	# 	@holiday = Holiday.find(params[:id])
	# end

	# def create
	# 	@holiday = current_user.holidays.build(params[:holiday])
	# 	if @holiday.save
	# 		flash[:notice]= "Feriado registrado exitosamente."
	# 		redirect_to holidays_path
	# 	else
	# 		render :action => 'new'
	# 	end
	# end

	# def update
	#   @holiday = Holiday.find(params[:id])
	 
	#   respond_to do |format|
	#     if @holiday.update_attributes(params[:holiday])
	#       format.html  { redirect_to(holidays_path,
	#                     :notice => 'Feriado Actualizado exitosamente.') }
	#       format.json  { head :no_content }
	#     else
	#       format.html  { render :action => "edit" }
	#       format.json  { render :json => @holiday.errors,
	#                     :status => :unprocessable_entity }
	#     end
	#   end
	# end
end

app/controllers/home_controller.rb
#encoding=utf-8
class HomeController < ApplicationController
  def index
  end

  def configurar
  	@current_user = current_user
  end

  
  def actualizar_usuario
	  @current_user = current_user
	 
	  respond_to do |format|
	    if @current_user.update_attributes(params[:user])
	      format.html  { redirect_to(root_path,
	                    :notice => 'Datos de Envío Actualizados exitosamente.') }
	      format.json  { head :no_content }
	    else
	      format.html  { render :action => "edit" }
	      format.json  { render :json => @holiday.errors,
	                    :status => :unprocessable_entity }
	    end
	  end
  end

  def send_email_test

  	User.envio_masivo
  	redirect_to root_path, :notice => "Email enviado"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/holidays_helper.rb
module HolidaysHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
  <div id="errorExplanation", class="alert alert-error">
    <h6><%= pluralize(@client.errors.count, "error") %> prohibited
        this client from being saved:</h6>
    <ul>
    <% @client.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :company_name %><br />
    <%= f.text_field :company_name %>
  </div>
  <div class="field">
    <%= f.label :contact_name %><br />
    <%= f.text_field :contact_name %>
  </div>
<div class="field">
    <%= f.label :contact_surname %><br />
    <%= f.text_field :contact_surname %>
  </div>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <br />
  
  <div class="actions">
    <%= f.submit 'Guardar', :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editar Cliente</h1>
 
<%= render 'form' %>
 

<%= link_to 'Volver', clients_path, :class => "btn btn-primary btn-small" %>

app/views/clients/index.html.erb
<h2> Mis Clientes </h2>
<% if @clients.empty? %>
<div class="row">
	<div class="span4">
		<div class="alert alert-block">
			<a class="close" data-dismiss="alert">x</a>
			<h4 class="alert-heading"> Aún no cargó Ningún cliente. </h4>
			Comience ahora haciendo click en el botón de abajo.
		</div>
	</div>
</div>
<%else%>
	<%= will_paginate @collection, :renderer => BootstrapPagination::Rails%>
	<table>
		<thead>
			<th> Compañia </th>
			<th> Nombre de Contacto </th>
			<th> Apellido de Contacto </th>
			<th> email</th>
			<th> </th>
			<th> </th>
		</thead>
		<tbody>

		<% @clients.each do |client| %>
			<tr>
	           		<td><%= client.company_name %></td>
	           		<td><%= client.contact_name %></td>
	           		<td><%= client.contact_surname %></td>
	           		<td><%= client.email %></td>
	           		<td><%= link_to "Editar", edit_client_path(client), :class => "btn btn-primary btn-mini"  %></td>
	           		<td><%= link_to "Eliminar", client_path(client), :method => :delete,:confirm => "¿Está seguro que desea eliminar al cliente #{client.full_name} ?", :class => "btn btn-primary btn-mini"  %></td>
	        </tr>
	    <%end %>	
	           

		</tbody>
	</table>
	<br />
	<br />
<%end%>
<%= link_to "Agregar un Cliente", new_client_path, :class => "btn btn-primary btn-large"%> 

app/views/clients/new.html.erb
<h1>Nuevo Cliente</h1>
 
<%= render 'form' %>
 
<%= link_to 'Volver', clients_path, :class => "btn btn-primary btn-small" %>

app/views/holidays/_form.html.erb
<%= form_for(@holiday) do |f| %>
  <% if @holiday.errors.any? %>
  <div id="errorExplanation", class="alert alert-error">
    <h6><%= pluralize(@holiday.errors.count, "error") %> prohibited
        this holiday from being saved:</h6>
    <ul>
    <% @holiday.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_field :description %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.date_select :date %>
  </div>
  <br />
  
  <div class="actions">
    <%= f.submit 'Guardar', :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/holidays/edit.html.erb
<h1>Editar Feriado</h1>
 
<%= render 'form' %>
 

<%= link_to 'Volver', holidays_path, :class => "btn btn-primary btn-small" %>

app/views/holidays/index.html.erb
<h2> Mis Feriados </h2>
<% if @holidays.empty? %>
	<div class="row">
	<div class="span4">
		<div class="alert alert-block">
			<a class="close" data-dismiss="alert">x</a>
			<h4 class="alert-heading"> Aún no cargó su calendario. </h4>
			Comience ahora haciendo click en el botón de abajo.
		</div>
	</div>
</div>	
<%else%>
	<%= will_paginate @collection, :renderer => BootstrapPagination::Rails%>
	<table>
		<thead>
			<th> Descripción </th>
			<th> Fecha </th>
			<th> </th>
			<th> </th>
		</thead>
		<tbody>
		<% @holidays.each do |holiday| %>
			<tr>
	           		<td><%= holiday.description %></td>
	           		<td><%= holiday.date %></td>
	           		<td><%= link_to "Editar", edit_holiday_path(holiday), :class => "btn btn-primary btn-mini"  %></td>
	           		<td><%= link_to "Eliminar", holiday_path(holiday), :method => :delete,:confirm => '¿Está seguro que desea eliminar el feriado?', :class => "btn btn-primary btn-mini" %></td>
	        </tr>
	    <%end %>	
	           

		</tbody>
	</table>
	<br />
<%end%>
<%= link_to "Agregar un feriado", new_holiday_path, :class => "btn btn-primary btn-large"%> 

app/views/holidays/new.html.erb
<h1>Nuevo Feriado</h1>
 
<%= render 'form' %>
 
<%= link_to 'Volver', holidays_path, :class => "btn btn-primary btn-small" %>

app/views/home/configurar.html.erb
<h2>Configurar datos de Envío </h2>
<div class="alert alert-info">
  <strong>Importante</strong>
   Estos datos representan:
   <ul>
      <li> First Name & Last Name: Serán la firma de su email.</li> 
      <li> Days: Indican la cantidad de días de anticipación con la que se mandará su mensaje automático. </li> 
      <li> Message: Es el contenido de su email. Se puede incluir marcado html y estio en línea </li> 
        
   </ul>
</div>
<%= form_for(@current_user, :url => actualizar_usuario_path) do |f| %>
  <% if @current_user.errors.any? %>
  <div id="errorExplanation", class="alert alert-error">
    <h6><%= pluralize(@current_user.errors.count, "error") %> prohibited
        this user from being saved:</h6>
    <ul>
    <% @current_user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
  <% end %>
 
  <div class="field">
    <%= f.label :first_name %><br />
    <%= f.text_field :first_name %>
  </div>
  <div class="field">
    <%= f.label :last_name %><br />
    <%= f.text_field :last_name %>
  </div>
  <div class="field">
    <%= f.label :days %><br />
    <%= f.text_field :days %>
  </div>
  <div class="field">
    <%= f.label :message %><br />
    <%= f.text_area :message, :size => "30x6" %>
  </div>

  
  <br />
  
  <div class="actions">
    <%= f.submit 'Guardar', :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/home/index.html.erb
      <!-- Main hero unit for a primary marketing message or call to action -->
      <div class="hero-unit">
        <h1>Notificador de feriados</h1>
        <p>Esta aplicación le permitirá advertir con tiempo a sus clientes los días que no trabajará de acuerdo a los feriados que indique en su calendario anual de días no laborables</p>
        <p><%= link_to "Sign Up Now! It's free", new_user_registration_path, :class => "btn btn-primary btn-large" %></p>
      </div>

      <!-- Example row of columns -->
      <div class="row">
        <div class="span4">
          <h2>Notificación Automática</h2>
          <p>Automatice la notificación de sus días no laborables. Fácil interfáz configurable. Cargue sus datos personales, lista de clientes y calendario de feriados y despreocúpese de olvidar notificar un feriado a sus clientes.</p>
          <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/hero.html#">Ver Detalles »</a></p>
        </div>
        <div class="span4">
          <h2>Envío Masivo de Emails</h2>
          <p>Hasta 200 emails por día con cuenta free. Consulte planes especiales.</p>
          <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/hero.html#">Ver Detalles »</a></p>
       </div>
        <div class="span4">
          <h2>Emails personalizados</h2>
          <p>Contamos con templates que pueden ser adaptados a su medida. También puede incluir su propio diseño</p>
          <p><a class="btn" href="http://twitter.github.com/bootstrap/examples/hero.html#">Ver Detalles »</a></p>
        </div>
      </div>

      <hr>

      <footer>
        <p>© EmanuelCadems 2012</p>
      </footer>


  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<!-- saved from url=(0054)http://twitter.github.com/bootstrap/examples/hero.html -->
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <title>Clase4</title>
  <%= stylesheet_link_tag  "bootstrap", "bootstrap.min","bootstrap-responsive","bootstrap-responsive.min","pagination",:media => "all" %>
  <%= javascript_include_tag  "application" %>
  <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Le styles -->
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/ico/favicon.ico">
    <link rel="apple-touch-icon-precomposed" sizes="144x144" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-144-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-114-precomposed.png">
    <link rel="apple-touch-icon-precomposed" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-72-precomposed.png">
    <link rel="apple-touch-icon-precomposed" href="http://twitter.github.com/bootstrap/assets/ico/apple-touch-icon-57-precomposed.png">
  </head>

  <body>
    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <%= link_to "Clase4", root_path, :class => :brand %>
          <div class="nav-collapse collapse">
          <% if user_signed_in? %>
                <ul class="nav">
                  <li><%= link_to "Mis Clientes", clients_path %></li>
                  <li><%= link_to "Mis Feriados", holidays_path %></li>                  
                  <li><%= link_to "Configurar datos de Envío", configurar_path %></li>                  
                  <li><%= link_to "Enviar email de prueba", sending_email_path %></li>                  
                  
                  
                </ul>
                <div class="navbar-form pull-right">
                  <ul class="nav">
                    <li><%= link_to("Cerrar Sesión", destroy_user_session_path, :method =>:delete) %></li>
                    <li><%= link_to current_user.email, edit_user_registration_path %></li>
                  </ul>                  
                </div>
          <%else%>          
            <%= form_for(@user,:url => user_session_path, :html => {:class => "navbar-form pull-right"}) do |f| %>      
              <%= f.email_field :email, :class => :span2, :required => true, :placeholder => :Email %>           
              <%= f.password_field :password, :class => :span2, :placeholder => :Password %>            
              <%= f.submit "Sign in", :class => :btn %> 
              <%= link_to "Sign Up Now!", new_user_registration_path, :class => "btn btn-primary btn-small" %>
            <%end %>
            <br />
            

          <%end%>    
          </div><!--/.nav-collapse -->
          
        </div>
      </div>
    </div>
    <div class="container">
      <% if notice %>
        <div class="alert alert-success"><%= notice %></div>
      <% end%>
      <% if alert %>
        <div class="alert alert-info"><%= alert %></div>
      <%end%>
    
  	<%= yield %>

    </div> <!-- /container -->

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="./Bootstrap, from Twitter_files/jquery.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-transition.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-alert.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-modal.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-dropdown.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-scrollspy.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-tab.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-tooltip.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-popover.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-button.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-collapse.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-carousel.js"></script>
    <script src="./Bootstrap, from Twitter_files/bootstrap-typeahead.js"></script>

</body></html>